### ISSUE TITLE
Hitting issues trying to use UUID instead of ID as primary key

### ISSUE THREAD

**Issue by kevinjalbert** [nedap/mysql-binuuid-rails#16]
I'm trying to use UUIDs instead of IDs as my primary key. I'm using:
- rails 5.2.0
- mysql-binuuid-rails 1.1.0
- mysql 5.6.40

My code mostly looks like the following: https://gist.github.com/kevinjalbert/07ec608500680e9d6fb4446e59f12f38

From a single model's perspective everything works. I can create and access the model using the `id` field (which is really a `binuuid`).

```
pry(main)> User.create
   (0.4ms)  SET NAMES utf8mb4,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
   (0.8ms)  BEGIN
  User Create (0.7ms)  INSERT INTO `users` (`id`) VALUES (x'289ae6e6d1c8432ba0fa8579933cc577')
   (2.2ms)  COMMIT
=> #<User:0x0000557e40a3ca78 id: "289ae6e6-d1c8-432b-a0fa-8579933cc577">
```

```
pry(main)> user = User.find("289ae6e6-d1c8-432b-a0fa-8579933cc577")
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = x'289ae6e6d1c8432ba0fa8579933cc577' LIMIT 1
=> #<User:0x0000557e40a89558 id: "289ae6e6-d1c8-432b-a0fa-8579933cc577">
```
I hit some interesting issues when trying to do relationships with it though:

```
pry(main)> user.posts.create
   (0.5ms)  BEGIN
  Post Create (1.0ms)  INSERT INTO `posts` (`id`, `user_id`) VALUES (x'082c13a29bc345df8b01f0e6e0e80d5a', x'32383961653665362d643163382d343332622d613066612d383537393933336363353737')
   (0.4ms)  ROLLBACK
ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column 'user_id' at row 1: INSERT INTO `posts` (`id`, `user_id`) VALUES (x'082c13a29bc345df8b01f0e6e0e80d5a', x'32383961653665362d643163382d343332622d613066612d383537393933336363353737')
from /usr/local/bundle/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query'
```

I don't know where the long value for the `user_id` is coming from here:

```
pry(main)> user.id
=> "289ae6e6-d1c8-432b-a0fa-8579933cc577"
```

-----

I've dug into this a bit more and it looks like the string `uuid` is being casted again as it goes into the database. At least that is what I'm seeing (as the values match-up):

```
 pry(main)> user.id.unpack("H*")[0]
=> "32383961653665362d643163382d343332622d613066612d383537393933336363353737"
```
-- https://github.com/nedap/mysql-binuuid-rails/blob/master/lib/mysql-binuuid/type.rb#L19

-----

Any suggestion on how to proceed? Maybe I'm using this gem the wrong way, or I'm going against the grain in trying to use `uuid` values instead of `id`s.

**Comment by kevinjalbert** [comment]
@markoudev I get the same error with that approach. I suspect it is following the same _double unpacking_ code path.

I'm not too familiar with the ActiveRecord side of things from a casting perspective. It sounds to me that _"the first thing that comes to mind is avoiding double unpacking by checking if it's already unpacked"_ approach would work, and would be contained to where the unpacking happens. 

I worry if there might be some edge case in that check though? Fortunately, UUIDs follow a fairly standard format and thus a quick check wouldn't be terrible from my perspective.

**Comment by markoudev** [comment]
I was digging into this a little more, and got the same error. I created two models with UUIDs as their primary key, and with a reference to each other. Then I realised I forgot to make the reference column a binary column as well.

When I specified that it worked.

Then I looked at your gist again, and found that in `Post` you say it `belongs_to :user`. That means that there is a column named `user_id`. Since the `id` of a `User` in your example is a UUID as well, you need to specify the attribute on `Post`:

`attribute :user_id, MySQLBinUUID::Type.new`

Is this a silly thing something we looked over completely? 😅

**Comment by markoudev** [comment]
I'm closing this to clean up the open issues.
