### ISSUE TITLE
Any workaround for the missing x in rails 5 with uniqueness validation?

### ISSUE THREAD

**Issue by DamianPereira** [nedap/mysql-binuuid-rails#36]
I'm hitting the issue mentioned in the README under known issues. I have a query like:
`ModeAl.joins(ModelB).where(thing_id: an_id).to_sql`, this returns a query without the x, which doesn't work.

Is there any workaround for this?

**Comment by markoudev** [comment]
Sorry for the late response, I was on holiday 😄  Unfortunately I'm not aware of any workaround right now. The only thing I can think of right now is performing the uniqueness validation yourself and not through Rails' validators. It's no option to update Rails?

**Comment by DamianPereira** [comment]
No problem, thanks for answering. By "update rails" you mean that rails 6 fixes this?

**Comment by markoudev** [comment]
Rails 6 would work, but upgrading to Rails 5.1 would be enough.

**Comment by DamianPereira** [comment]
I'm running rails 5.2.3 and I'm getting the same issue, I can try to get a minimal repro scenario.

**Comment by DamianPereira** [comment]
I've noticed that this was caused by different reasons, probably related to https://github.com/rails/rails/issues/30278, but I'm also seeing this when doing multiple nested joins, there comes a moment where rails does not understand that the id field should be serialized. 

Do you know if the class_name issue and association issue was fixed upstream in rails 6 or if there is any current workaround?

**Comment by markoudev** [comment]
I'm not sure to be honest. I've just returned to Rails development after some other adventures, and haven't been informed nor came across this issue just yet.
