### ISSUE TITLE
Pad odd digit uuid values to prevent mysql syntax errors

### ISSUE THREAD

**Issue by shevaun** [nedap/mysql-binuuid-rails#7]
Hi,

I've noticed that when we make an ActiveRecord query with a uuid with an odd number of digits, mysql raises an exception: 

```
SELECT  `item_uuids`.* FROM `item_uuids` WHERE `item_uuids`.`uuid` = x'6' ORDER BY 
`item_uuids`.`id` ASC LIMIT 1

ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the 
manual that corresponds to your MySQL server version for the right syntax to use near 'x'6'
```

Mysql explains why this is raised [here](https://dev.mysql.com/doc/refman/5.7/en/hexadecimal-literals.html).

We've just switched from the [activeuuid](https://github.com/jashmenn/activeuuid) gem to this one, so I checked how they get around this issue and it appears they pad the value too:

```
ItemUUID Load (0.4ms)  SELECT  `item_uuids`.* FROM `item_uuids` WHERE `item_uuids`.`uuid`
 = x'00000000000000000000000000000036'  ORDER BY `item_uuids`.`id` ASC LIMIT 1
```

If you're ok with the idea let me know if you're happy to implement it or whether I should create a PR.

Thanks

**Comment by markoudev** [comment]
Hello, thanks for reporting this! And pardon me for the late reply, I didn't get a notification in my e-mail. Another approach would be to pad the uuid before you're going to use it in a query.

I'm curious to the situation in which you would have a uuid that doesn't look like a uuid, could you describe when this would happen?

**Comment by shevaun** [comment]
We've got a method that takes a value which can be a primary key or a uuid and tries to find records based on one or the other. So it if doesn't match on a primary key it thinks the value is a uuid.

**Comment by markoudev** [comment]
The thing I'm thinking about is who's responsibility it is to make sure the query doesn't break. This gem is specifically meant to store uuids as binary values, and that's it. It expects nothing else but a uuid, which always have a proper number of digits for the query.

My current thought is that it would be the responsibility of the application to make sure valid uuids are being used if you're seeking for records by uuid, and not the responsibility of this gem.

The method that you have that does a fallback to searching a record by uuid when it doesn't find anything when searching for its id. This method could check if the value you're going to use in the query looks like a uuid, i.e. something like:

```ruby
if value =~ /[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/
  # looks like a uuid, so let's search for a uuid
end
```

And then you're sure you put in the proper values.

**Comment by shevaun** [comment]
Yeah, I think that's a reasonable assumption. Will change our code :)

The other issue we're having (and it seems to affect all the uuid gems I've tried), is that having `validates_uniqueness_of :uuid` in a model doesn't encode the uuid properly (it's missing the `x`) so it never matches on uuid. I think it must be something to do with the way Rails 5 (we're upgrading from Rails 4 currently) handles the attribute types, but I couldn't pinpoint it exactly. I've changed our code to do the SQL query ourselves, but just thought I'd mention it to you in case you wanted to look into it.

**Comment by markoudev** [comment]
Thanks for pointing that out, I'll look into it.

**Comment by markoudev** [comment]
Hi @shevaun -- I've added a PR with a test to ensure uniqueness validation works, and it seems to be passing: https://github.com/nedap/mysql-binuuid-rails/pull/8

If you believe this is a bug within this gem please file an issue ^^

**Comment by eiapopeia** [comment]
@markoudev wrote:
> My current thought is that it would be the responsibility of the application to make sure valid uuids are being used if you're seeking for records by uuid, and not the responsibility of this gem.

I think it would be really helpful if the gem provides the Regex for the `uuid` or a helper to check strings. So it would be easier for applications to check the proper form.

I am thinking of something like:
``` ruby
  UUID_REGEX = /[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/

  def proper_uuid?(uuid)
    return false if uuid.blank? ||
      !uuid.is_a?(String)
    uuid.match?(UUID_REGEX)
  end
```
(I do not know where to put this or if this is wanted, so I am just posting this here).
